language: node_js
dist: trusty
sudo: required
node_js:
  - 'node'

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome

install:
  - npm install

addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable
